### ISSUE TITLE
Installation issue with conda

### ISSUE THREAD

**Issue by cfandel** [Mirebeau/AdaptiveGridDiscretizations#4]
Hello, 
I'm having some installation issues with conda. 
I would like to be able to use this package as part of other projects where it would be nice to be able to install it into other existing environments with conda.

I first tried downloading the .yaml file and creating a new environment with it:
`conda env create --file agd-hfm.yaml`
That environment didn't include the agd package and returned a "module not found" error on import.

Then I tried installing the agd-hfm package:
`conda install -c agd-lbr hfm`
Same error on import.

Then I tried installing the agd package: 
`conda install agd -c agd-lbr`

This solved the module not found error upon import, but then when I tried to actually run the solver
`hfmOut = hfmIn.Run()`
 I got another "module not found" error. This error also happens when I try to install the agd package in a different environment (not from the yaml file).
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-28df913fd5a3> in <module>
      1 # Run the solver:
----> 2 hfmOut = hfmIn.Run()

~\Anaconda3\envs\agd-hfm\lib\site-packages\agd-0.1.12-py3.7.egg\agd\Eikonal\DictIn.py in Run(self, join, **kwargs)
    184                         else: return dictOut(out)
    185 
--> 186                 if   self.mode=='cpu': return to_dictOut(run_detail.RunSmart(self,**kwargs))
    187                 elif self.mode=='cpu_raw': return to_dictOut(run_detail.RunRaw(self.store,**kwargs))
    188                 elif self.mode=='cpu_transfer':

~\Anaconda3\envs\agd-hfm\lib\site-packages\agd-0.1.12-py3.7.egg\agd\Eikonal\run_detail.py in RunSmart(hfmIn, returns, co_output, cache)
    139         # Call to the HFM library
    140         if returns=='in_raw': return hfmIn_raw
--> 141         hfmOut_raw = RunDispatch(hfmIn_raw,GetBinaryDir("FileHFM","HFMpy"))
    142         if returns=='out_raw': return hfmOut_raw
    143 

~\Anaconda3\envs\agd-hfm\lib\site-packages\agd-0.1.12-py3.7.egg\agd\Eikonal\LibraryCall.py in RunDispatch(params, bin_dir)
     51         if bin_dir is None:
     52                 moduleName = 'HFMpy.HFM_'+modelName
---> 53                 HFM = importlib.import_module(moduleName)
     54                 hfm = HFM.HFMIO()
     55                 SetInput(hfm,params)

~\Anaconda3\envs\agd-hfm\lib\importlib\__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

~\Anaconda3\envs\agd-hfm\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

~\Anaconda3\envs\agd-hfm\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

~\Anaconda3\envs\agd-hfm\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'HFMpy.HFM_Isotropic2
````

What would you recommend to solve this issue? Thanks in advance!

PS: Additionally, when I try simply cloning the entire repository and running the notebooks within it offline, I get the following error:
````
ERROR :ERROR : the HFMpy library is not found, and the path to the FileHFM binaries is not set

You can set the path to the FileHFM compiled binaries, as follows : 

>>> agd.Eikonal.LibraryCall.FileHFM_binary_dir = 'path/to/FileHFM/bin'



In order to do this automatically in the future, please set this path 
in the first line of a file named 'FileHFM_binary_dir.txt' in the current directory

>>> with open('FileHFM_binary_dir.txt','w+') as file: file.write('path/to/FileHFM/bin')

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-14-9fb6e9fb9246> in <module>
----> 1 hfmOut = hfmIn.Run()

~\Documents\GitHub\AdaptiveGridDiscretizations\agd\Eikonal\DictIn.py in Run(self, join, **kwargs)
    249                         else: return dictOut(out)
    250 
--> 251                 if   self.mode=='cpu': return to_dictOut(run_detail.RunSmart(self,**kwargs))
    252                 elif self.mode=='cpu_raw': return to_dictOut(run_detail.RunRaw(self.store,**kwargs))
    253                 elif self.mode=='cpu_transfer':

~\Documents\GitHub\AdaptiveGridDiscretizations\agd\Eikonal\run_detail.py in RunSmart(hfmIn, co_output, cache, returns)
    147         # Call to the HFM library
    148         if returns=='in_raw': return hfmIn_raw
--> 149         hfmOut_raw = RunDispatch(hfmIn_raw,GetBinaryDir("FileHFM","HFMpy"))
    150         if returns=='out_raw': return hfmOut_raw
    151 

~\Documents\GitHub\AdaptiveGridDiscretizations\agd\Eikonal\LibraryCall.py in GetBinaryDir(execName, libName)
     88         try:
     89                 # Try reading the file
---> 90                 with open(fileName,'r') as f:
     91                         binary_dir = f.readline().replace('\n','')
     92                         if binary_dir=="None":

FileNotFoundError: [Errno 2] No such file or directory: 'FileHFM_binary_dir.txt'
````

**Comment by Mirebeau** [comment]
Dear cfandel

Thanks for the feedback. The conda installation had not been tested in a while, and indeed some things needed to be sorted out.

Issue 1 : agd package was not found
Fix : agd dependency added in agd-hfm.yaml

Issue 2 : the HFMpy.HFM_Isotropic2 module was not found
Reason : the python 3.8 version of the HFMpy package was empty, due to setuptools not supporting python 3.8 at the time
Fix 1 : set python=3.7 in agd-hfm.yaml
Fix 2 : the python 3.8 version of HFMpy is now corrected (setuptools has been fixed meanwhile), EXCEPT ON WINDOWS.
I have applied the two fixes, although any of the two alone does the job.
--> Please tell me if this works for you.


Issue 3 : No such file or directory: 'FileHFM_binary_dir.txt'
Reason : this is an alternative way of using the hfm library, but you have first to compile the HamiltonFastMarching (hfm) library from the sources. Currently it is the only way to run the latest version on windows.

Best

**Comment by Mirebeau** [comment]
The last versions of the agd and hfm library are now available on conda, for all three platforms, for Python versions 3.5, 3.6, 3.7 and 3.8, and install with conda environment agd-hfm.yaml

Please check again,

**Comment by cfandel** [comment]
This solved the problem and I can now run the notebooks on my own computer successfully. Thank you!
